"""initial

Revision ID: 07ac19cd9877
Revises: 
Create Date: 2023-07-10 00:10:25.251311

"""
from alembic import op
import sqlalchemy as sa
import gtservice.db


# revision identifiers, used by Alembic.
revision = '07ac19cd9877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('actuality', sa.Enum('actual', 'outdated', name='actuality'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_language'), 'words', ['language'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_definitions_id'), 'definitions', ['id'], unique=False)
    op.create_index(op.f('ix_definitions_text'), 'definitions', ['text'], unique=False)
    op.create_table('examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_id'), 'examples', ['id'], unique=False)
    op.create_index(op.f('ix_examples_text'), 'examples', ['text'], unique=False)
    op.create_table('word_synonyms',
    sa.Column('from_word_id', sa.Integer(), nullable=False),
    sa.Column('to_word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['to_word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('from_word_id', 'to_word_id')
    )
    op.create_table('word_translations',
    sa.Column('from_word_id', sa.Integer(), nullable=False),
    sa.Column('to_word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['to_word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('from_word_id', 'to_word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_translations')
    op.drop_table('word_synonyms')
    op.drop_index(op.f('ix_examples_text'), table_name='examples')
    op.drop_index(op.f('ix_examples_id'), table_name='examples')
    op.drop_table('examples')
    op.drop_index(op.f('ix_definitions_text'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_id'), table_name='definitions')
    op.drop_table('definitions')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_language'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
